"""
PDF Generator Lambda
--------------------
Receives structured product recommendations from the Orchestrator Lambda,
renders a branded HTML quotation template, converts it to PDF using
WeasyPrint, and saves it to the S3 output bucket.

Dependencies (package as a Lambda Layer):
  pip install weasyprint==60.2 --target ./layer/python
"""

import io
import json
import logging
import os
from datetime import datetime

import boto3

logger = logging.getLogger()
logger.setLevel(os.environ.get("LOG_LEVEL", "INFO"))

OUTPUT_BUCKET = os.environ["OUTPUT_BUCKET"]
AWS_REGION    = os.environ["AWS_REGION_NAME"]

s3_client = boto3.client("s3", region_name=AWS_REGION)


# ── HTML Template ─────────────────────────────────────────────────────────

def build_html(quotation_id: str, requirements: str, data: dict, generated_at: str) -> str:
    products  = data.get("recommended_products", [])
    total     = data.get("total_usd", 0)
    notes     = data.get("notes", "")
    summary   = data.get("customer_summary", requirements)
    date_str  = datetime.fromisoformat(generated_at.rstrip("Z")).strftime("%d %B %Y")

    rows = ""
    for p in products:
        rows += f"""
        <tr>
          <td>{p.get('sku', 'N/A')}</td>
          <td><strong>{p.get('product_name', '')}</strong><br>
              <small>{p.get('description', '')}</small></td>
          <td class="num">{p.get('quantity', 0)}</td>
          <td class="num">${p.get('unit_price_usd', 0):,.2f}</td>
          <td class="num"><strong>${p.get('subtotal_usd', 0):,.2f}</strong></td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: #1a1a1a; padding: 40px; }}
  .header {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 32px; }}
  .logo {{ font-size: 28px; font-weight: 700; color: #0052cc; letter-spacing: -1px; }}
  .logo span {{ color: #ff6b35; }}
  .meta {{ text-align: right; color: #555; font-size: 12px; line-height: 1.8; }}
  .meta .ref {{ font-size: 18px; font-weight: 700; color: #0052cc; }}
  h2 {{ font-size: 15px; margin: 20px 0 6px; color: #333; border-bottom: 2px solid #0052cc; padding-bottom: 4px; }}
  .summary-box {{ background: #f4f7fb; border-left: 4px solid #0052cc; padding: 12px 16px; margin-bottom: 24px; border-radius: 4px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 8px; }}
  th {{ background: #0052cc; color: #fff; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; }}
  td {{ padding: 10px 12px; border-bottom: 1px solid #e8e8e8; vertical-align: top; }}
  tr:nth-child(even) td {{ background: #fafbfc; }}
  .num {{ text-align: right; }}
  .total-row td {{ background: #eef3fb; font-weight: 700; font-size: 14px; border-top: 2px solid #0052cc; }}
  .notes {{ margin-top: 24px; background: #fffbf0; border: 1px solid #f0c040; border-radius: 4px; padding: 12px 16px; }}
  .footer {{ margin-top: 40px; font-size: 11px; color: #888; text-align: center; border-top: 1px solid #ddd; padding-top: 12px; }}
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="logo">Net<span>pro</span></div>
    <div style="margin-top:4px;color:#555;font-size:12px;">Network Infrastructure Solutions</div>
  </div>
  <div class="meta">
    <div class="ref">Quotation #{quotation_id}</div>
    <div>Date: {date_str}</div>
    <div>Valid for 30 days</div>
  </div>
</div>

<h2>Project Summary</h2>
<div class="summary-box">{summary}</div>

<h2>Customer Requirements</h2>
<p style="color:#555;line-height:1.6;margin-bottom:16px;">{requirements}</p>

<h2>Recommended Products</h2>
<table>
  <thead>
    <tr>
      <th style="width:12%">SKU</th>
      <th style="width:44%">Product</th>
      <th style="width:10%" class="num">Qty</th>
      <th style="width:16%" class="num">Unit Price</th>
      <th style="width:18%" class="num">Subtotal</th>
    </tr>
  </thead>
  <tbody>
    {rows}
    <tr class="total-row">
      <td colspan="4" style="text-align:right;">TOTAL (USD)</td>
      <td class="num">${total:,.2f}</td>
    </tr>
  </tbody>
</table>

{"<div class='notes'><strong>Notes:</strong> " + notes + "</div>" if notes else ""}

<div class="footer">
  This quotation was generated by Netpro AI Sales Assistant &bull; Prices subject to change &bull; All prices in USD excluding taxes &bull;
  Generated: {generated_at}
</div>

</body>
</html>"""


# ── Main handler ─────────────────────────────────────────────────────────

def lambda_handler(event, context):
    try:
        quotation_id  = event["quotation_id"]
        requirements  = event["requirements"]
        recommendations = event["recommendations"]
        generated_at  = event.get("generated_at", datetime.utcnow().isoformat() + "Z")

        html_content = build_html(quotation_id, requirements, recommendations, generated_at)

        # Try WeasyPrint (requires Lambda layer); fall back to HTML if not available
        try:
            from weasyprint import HTML as WP_HTML
            pdf_bytes = WP_HTML(string=html_content).write_pdf()
            content_type = "application/pdf"
            file_ext = "pdf"
        except ImportError:
            logger.warning("WeasyPrint not available — saving HTML instead. Add the PDF layer.")
            pdf_bytes = html_content.encode("utf-8")
            content_type = "text/html"
            file_ext = "html"

        # Save to S3
        date_prefix = datetime.utcnow().strftime("%Y/%m/%d")
        s3_key = f"quotations/{date_prefix}/Netpro-Quotation-{quotation_id}.{file_ext}"

        s3_client.put_object(
            Bucket=OUTPUT_BUCKET,
            Key=s3_key,
            Body=pdf_bytes,
            ContentType=content_type,
            Metadata={
                "quotation-id": quotation_id,
                "generated-at": generated_at,
            },
        )

        logger.info(f"[{quotation_id}] Saved to s3://{OUTPUT_BUCKET}/{s3_key}")
        return {"quotation_id": quotation_id, "s3_key": s3_key, "status": "success"}

    except Exception as e:
        logger.exception(f"PDF generation failed: {e}")
        raise
